### ISSUE TITLE
can't compile on osx (0.82 thru 0.84 actually)

### ISSUE THREAD

**Issue by mbunkus** [mbunkus/mtx-trac-import-test#23]
**Reported by fishrunsrap on 12 Feb 2004 01:44 UTC**
mkvtoolnix won't compile on osx. I am using the most up-to-date developer 
stuff from apple (gcc3.3, wchar.h support, etc etc) and I've installed the latest 
FLAC, iconv, ogg, libmatroska, and libebml by hand with no problems.

./configure runs ok and finds everything. but first, the avilib stuff fails, with the 
following compile time error:

gcc -DHAVE_CONFIG_H -I. -I. -I.. -I.. -I../src -I../src/common    -Wall -Wno-
sign-compare -Wno-comment -D_LARGEFILE64_SOURCE 
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64      -O3 -funroll-loops 
-ffast-math -DLINUX -Wall -c `test -f 'avilib.c' || echo './'`avilib.c
avilib.c: In function `AVI_open_output_file':
avilib.c:622: error: `O_BINARY' undeclared (first use in this function)
avilib.c:622: error: (Each undeclared identifier is reported only once
avilib.c:622: error: for each function it appears in.)
avilib.c:623: error: `S_IGRP' undeclared (first use in this function)
make[*** [avilib.o](2]:) Error 1
make[*** [all-recursive](1]:) Error 1
make: *** [Error 2
corenet-1290:~/Documents/UNIXXX/matroska/mkvtoolnix-0.8.4 fish$ 

... I even went so far as to replace the avilib files with known working ones 
from the transcode distro. that makes avilib work, but then I get the following 
error:

g++ -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -I../../src -I../../avilib-0.6.10  -I.    
-Wall -Wno-sign-compare -Wno-comment -D_LARGEFILE64_SOURCE 
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64       -Wshadow -c -o 
common.o `test -f 'common.cpp' || echo './'`common.cpp
common.cpp: In function `int utf8_init(const char*)':
common.cpp:473: error: `locale_charset' undeclared (first use this function)
common.cpp:473: error: (Each undeclared identifier is reported only once for 
   each function it appears in.)
common.cpp: In function `void* _safememdup(const void*, long unsigned int, 
   const char*, int)':
common.cpp:681: warning: int format, size_t arg (arg 4)
common.cpp: In function `void* _safemalloc(long unsigned int, const char*, 
int)
   ':
common.cpp:693: warning: int format, size_t arg (arg 4)
common.cpp: In function `void* _saferealloc(void*, long unsigned int, const 
   char*, int)':
common.cpp:702: warning: int format, size_t arg (arg 4)
make[3](all]): *** [Error 1
make[2](common.o]): *** [Error 1
make[1](all-recursive]): *** [Error 1
make: *** [all](all-recursive]) Error 2
corenet-1290:~/Documents/UNIXXX/matroska/mkvtoolnix-0.8.4 fish$ 

... I'd love to use mkvtoolnix on osx. let me know if I can provide any 
additional info. thanks!

-fish
